sudo: required
language: go
go:
  - "1.13.x"
services:
  - docker
jobs:
  include:
    - stage: test
      name: protos
      install: true
      script: make test
    - stage: test
      name: unit tests
      install: make install
      script: make test_unit
    - if: tag IS present AND fork = false
      stage: release
      name: release Python package
      install: skip
      script: make release
