sudo: required
language: go
go:
  - "1.10"
services:
  - docker
jobs:
  include:
    - stage: test
      name: protos
      install: true
      script: make test
    - stage: test
      name: unit tests
      install: make install 
      script: make test_unit
